### ISSUE TITLE
Torques from Rnea and equation of motion don't match

### ISSUE THREAD

**Issue by nunoguedelha** [laas/metapod#78]
If we compute the torques using RNEA, Tau=ID(q,dq,ddq), we get the expected reference torques (rnea.ref).
If we use the equation of motion, Tau=H*ddq+C, we get wrong torques. The issue is introduced by the use of optional parameter "prefer-fixed-axis=true" in simple_humanoid.config file . Refer to following comments for more details.

**Comment by olivier-stasse** [comment]
Fixed by  beb4f69
